import type { ARAdapter, ProjectContext, GeneratedFile } from "./types.js";
import type { ResolvedHarness } from "../models/harness.js";

export const codexAdapter: ARAdapter = {
  id: "codex",
  name: "Codex",
  instructionFile: "AGENTS.md",

  generateInstructions(ctx: ProjectContext, harness?: ResolvedHarness): GeneratedFile {
    let content = `# AgentHive — Agent Instructions\n\n`;
    content += `> Auto-generated by AgentHive.\n\n`;
    content += `## Setup\n\n`;
    content += `1. Read protocol: \`${ctx.hubPath}/PROTOCOL.md\`\n`;
    content += `2. Check tasks: \`${ctx.hubProjectPath}/tasks/BACKLOG.md\`\n`;
    content += `3. Claim, plan, build, review\n\n`;
    content += `## Project: ${ctx.projectName}\n\n`;
    if (ctx.projectDescription) content += `${ctx.projectDescription}\n\n`;
    content += `## Paths\n\n`;
    content += `- Hub: \`${ctx.hubPath}\`\n`;
    content += `- Project: \`${ctx.hubProjectPath}\`\n`;
    content += `- Repo: \`${ctx.repoPath}\`\n\n`;

    if (harness && harness.conventions.length > 0) {
      content += `## Conventions\n\n`;
      for (const conv of harness.conventions) {
        content += `- **${conv.name}**: ${conv.content.split("\n")[0]}\n`;
      }
      content += `\n`;
    }

    if (ctx.hasCollab) {
      content += `## Communication\n\n`;
      content += `Use JSONL channels in \`${ctx.hubProjectPath}/collab/channels/\` for discussion.\n\n`;
    }

    return { path: ctx.repoPath, filename: "AGENTS.md", content };
  },
};
