import type { ARAdapter, ProjectContext, GeneratedFile } from "./types.js";
import type { ResolvedHarness } from "../models/harness.js";

export const copilotAdapter: ARAdapter = {
  id: "copilot",
  name: "GitHub Copilot",
  instructionFile: "copilot-instructions.md",

  generateInstructions(ctx: ProjectContext, harness?: ResolvedHarness): GeneratedFile {
    let content = `# AgentHive — Copilot Instructions\n\n`;
    content += `> Auto-generated by AgentHive. Do not edit manually.\n\n`;
    content += `## Project\n\n`;
    content += `- **Name**: ${ctx.projectName}\n`;
    content += `- **Hub**: ${ctx.hubPath}\n`;
    content += `- **Project Hub**: ${ctx.hubProjectPath}\n\n`;
    content += `## Protocol\n\n`;
    content += `Read the AgentHive protocol: \`${ctx.hubPath}/PROTOCOL.md\`\n\n`;
    content += `### Task Workflow\n\n`;
    content += `1. Check \`${ctx.hubProjectPath}/tasks/BACKLOG.md\` for available tasks\n`;
    content += `2. Claim a task by creating \`lock.yaml\` in the task directory\n`;
    content += `3. Write \`plan.md\` before implementing\n`;
    content += `4. Implement, then update \`summary.md\`\n`;
    content += `5. Set status to \`review\` when done\n\n`;

    if (harness && harness.conventions.length > 0) {
      content += `## Conventions\n\n`;
      for (const conv of harness.conventions) {
        content += `### ${conv.name}\n\n`;
        content += `${conv.content}\n\n`;
      }
    }

    if (harness && Object.keys(harness.prompts).length > 0) {
      content += `## Prompt Templates\n\n`;
      for (const [key, prompt] of Object.entries(harness.prompts)) {
        content += `### ${key}\n\n`;
        content += `See: \`${prompt.path}\`\n\n`;
      }
    }

    return {
      path: ctx.repoPath + "/.github",
      filename: "copilot-instructions.md",
      content,
    };
  },
};
