import { homedir } from "node:os";
import { join } from "node:path";

export const DEFAULT_HUB_PATH = join(homedir(), ".agenthive");
export const CONFIG_FILE = "config.yaml";
export const REGISTRY_FILE = "registry.yaml";
export const PROTOCOL_FILE = "PROTOCOL.md";
export const AGENTS_DIR = "agents";
export const PROJECTS_DIR = "projects";
export const TASKS_DIR = "tasks";
export const BACKLOG_FILE = "BACKLOG.md";
export const TASK_YAML = "task.yaml";
export const LOCK_YAML = "lock.yaml";
export const PLAN_MD = "plan.md";
export const SUMMARY_MD = "summary.md";
export const SLUG_SEPARATOR = "--";
export const POINTER_FILE = ".agenthive.pointer.yaml";
export const COLLAB_DIR = "collab";
export const COLLAB_CONFIG_FILE = "collab.yaml";
export const COLLAB_CHANNELS_DIR = "channels";
export const COLLAB_PROFILES_DIR = "profiles";
export const TASK_THREAD_FILE = "thread.jsonl";
export const HARNESS_DIR = "harness";
export const HARNESS_MANIFEST_FILE = "harness.yaml";
export const HARNESS_CONVENTIONS_DIR = "conventions";
export const HARNESS_PROMPTS_DIR = "prompts";
export const HARNESS_SKILLS_DIR = "skills";
export const HARNESS_KNOWLEDGE_DIR = "knowledge";
export const SYNC_DIR = "sync";
export const SYNC_CONFIG_FILE = "github.yaml";
export const SYNC_ISSUE_MAP_FILE = "issue-map.yaml";
export const SYNC_PR_MAP_FILE = "pr-map.yaml";
